### ISSUE TITLE
Error: The file name must end with .xml

### ISSUE THREAD

**Issue by HosseinKurd** [Jamargle/SampleAR-Markers-#1]
Can not build project
because of :

/SampleAR-Markers--master/app/src/main/res/assets/marker_at16.patt
Error: The file name must end with .xml
Execution failed for task ':app:mergeDebugResources'.
> /SampleAR-Markers--master/app/src/main/res/assets/marker_at16.patt: Error: The file name must end with .xml

**Comment by Jamargle** [comment]
I have moved to the raw folder these files and now it works. 
Please, try again and let me know if it is still failing.
Thanks!
