### ISSUE TITLE
Content is not allowed in prolog.

### ISSUE THREAD

**Issue by FarrukhSaleem89** [Jamargle/SampleAR-Markers-#2]
when i am running this application on my android mobile then it blink and close and nothing show in logcat

**Comment by Jamargle** [comment]
Hi @FarrukhSaleem89 !
Sorry but right now I won't be able to check your problem. Please, give me 10 or 15 days and when I go back to my home I will be glad to help you :)

**Comment by Jamargle** [comment]
Hi again @FarrukhSaleem89 !
It should be working now.
